### ISSUE TITLE
[Question] Is the protocol for Oracle NoSQL publically available?

### ISSUE THREAD

**Issue by MisterSpicy** [oracle/nosql-go-sdk#1]
Hello, thanks for providing this project to the OSS community.

From the official Oracle NoSQL docs, it doesn't seem the binary protocol you appear to be using is part of the data sheet.  Is is publicly available, or is the protocol internal to Oracle?

I'd like to develop a connector in another not-officially-supported language, and am looking to see if this is possible?

Thanks

**Comment by zehliu** [comment]
@MisterSpicy  Thanks for your interest in the Oracle NoSQL project. The binary protocol is not publicly available for now, we have been discussing publishing the protocol to the community, we will make it as soon as we can.

**Comment by MisterSpicy** [comment]
Thanks for the quick response @zehliu!  Glad to hear it.  I will close this issue.
