### ISSUE TITLE
x509: certificate signed by unknown authority on Windows

### ISSUE THREAD

**Issue by mattn** [oracle/nosql-go-sdk#2]
I get always errors with trying examples/basic since Go on Windows does not support root certification. On Windows, you should set cfg.CertPath to `~/.oci/oci_api_key.pem` and InsecureSkipVerify = true for cloud iam.

```diff
diff --git a/examples/common.go b/examples/common.go
index 81a4b8a..6164a37 100644
--- a/examples/common.go
+++ b/examples/common.go
@@ -105,6 +105,9 @@ import (
 	"flag"
 	"fmt"
 	"os"
+	"path/filepath"
+	"runtime"
+	"strings"
 
 	"github.com/oracle/nosql-go-sdk/nosqldb"
 	"github.com/oracle/nosql-go-sdk/nosqldb/auth/cloudsim"
@@ -245,6 +248,18 @@ func CreateClient() (client *nosqldb.Client, err error) {
 		} else {
 			cfg.Region = region
 		}
+
+		if runtime.GOOS == "windows" {
+			fn := args.configFile
+			if strings.HasPrefix(fn, "~") {
+				home, err := os.UserHomeDir()
+				if err == nil {
+					fn = filepath.Join(home, fn[1:])
+				}
+			}
+			cfg.InsecureSkipVerify = true
+			cfg.CertPath = filepath.ToSlash(filepath.Join(filepath.Dir(fn), "oci_api_key.pem"))
+		}
 	} else {
 		cfg.Endpoint = args.endpoint
 	}
```
I know you already have sdkutil.ExpandPath and way to handle KeyFilePath. But current implementation does not have a way to get KeyFilePath from configurationProvider.

**Comment by zehliu** [comment]
Thanks for reporting this issue on Windows! 
When you have `cfg.InsecureSkipVerify` set to `true`, the certificate specified in `cfg.CertPath` is ignored, it does not get validated.  Setting `InsecureSkipVerify` to `true` should work.
```go
if runtime.GOOS == "windows" {
    cfg.InsecureSkipVerify = true
}
```

Skipping the server certificate validation should only be done in testing or in example programs like in this case, it is not recommended in production environments.

**Comment by mattn** [comment]
> When you have cfg.InsecureSkipVerify set to true, the certificate specified in cfg.CertPath is ignored, it does not get validated. Setting InsecureSkipVerify to true should work.

See https://github.com/oracle/nosql-go-sdk/blob/4d026c9045dd7c80d4dabde03d644946c862cf15/nosqldb/httputil/httpclient.go#L83

Current implementation looks CertPath.

**Comment by zehliu** [comment]
This is inside the `if` block
```go
if cfg.InsecureSkipVerify == false && cfg.CertPath != "" {
    certs, err := ioutil.ReadFile(cfg.CertPath)
...
```
in this case, the if condition evaluates to `false`, so `cfg.CertPath` is ignored.
BTW, the `oci_api_key.pem` looks like the private key of your OCI account, does not seem to be the desired server certificate.

**Comment by mattn** [comment]
Ah, right.  I was confused. Sorry. I'll send pull-request.

https://github.com/oracle/nosql-go-sdk/pull/3
