### ISSUE TITLE
DEBUG message in client.Query() "the QueryRequest is neither prepared nor bound to a QueryDriver"

### ISSUE THREAD

**Issue by Tragopoulos** [oracle/nosql-go-sdk#32]
Hello,

I'm following exactly the example provided from the package:

https://pkg.go.dev/github.com/oracle/nosql-go-sdk@v1.4.2/nosqldb#example-Client.Query 

and every time I make a request I see in the OCI FaaS logs the following message:

"2024/04/13 11:52:51.162768 UTC [DEBUG] the QueryRequest is neither prepared nor bound to a QueryDriver"

**Comment by dario-vega** [comment]
Could you provide the code you are using to make the connection? What value is used for the [log level](https://pkg.go.dev/github.com/oracle/nosql-go-sdk@v1.4.2/nosqldb/logger#LogLevel)?

I wonder if you can set this value to Warn instead of Debug, Trace, Fine? Why you need the DEBUG level?

```
	lcfg := nosqldb.LoggingConfig {
		// EDIT: change logger.Warn to logger.Fine for detailed output
		Logger: logger.New(os.Stdout, logger.Warn, false),
	}
	cfg.LoggingConfig = lcfg
```

**Comment by dario-vega** [comment]
Could you use `logger.Warn` to avoid the DEBUG message in the logs?

**Comment by connelly38** [comment]
@Tragopoulos this is a harmless message meant for debugging specific query issues. It is not indicative of a problem or error. As I'm sure you've seen, enabling `Fine` logging makes the library dump out a lot if internal information. You may want to consider using `Info` or `Warn`.

**Comment by Tragopoulos** [comment]
Thank you for the clarification.
